### ISSUE TITLE
Installing on a 64 bit ubuntu 14.0x is not straight forward

### ISSUE THREAD

**Issue by subramanyamVemu** [fish2000/instakit#4]
Hi 

It will be good to have detailed documentation of how to install on a 64 bit linux machine

Thanks
Bala

**Comment by subramanyamVemu** [comment]
The following apt-get installation got it through

sudo apt-get install libpng12-dev libtiff4-dev libwebp-dev
sudo apt-get install xcftools

**Comment by fish2000** [comment]
That is actually good to know, thanks – I have not personally installed it on Ubuntu 14 so I appreciate the feedback. 

Instakit was initially a pure-python module. It [depends on](https://github.com/fish2000/instakit/blob/master/requirements.txt) implementations and interfaces from [NumPy](http://www.numpy.org/), [SciPy](http://docs.scipy.org/doc/), and [Pillow](https://github.com/python-pillow/Pillow) (née [PIL](http://effbot.org/zone/pil-index.htm)) for both the optimized image math and the file-format I/O that the project needs.

The first three dev packages in your list are Pillow’s requirements, specifically.

I am not sure why you needed `xcftools` as I don’t do anything with it. One of Instakit’s currently not-directly-used and optional utilities, `instakit.utils.lutmap` does import the `imread` module by default (specifically [here](https://github.com/fish2000/instakit/blob/master/instakit/utils/lutmap.py#L10))… `imread` (which can be had [here](https://github.com/luispedro/imread)) can optionally use `xcftools` but doesn’t require it. 

Anyway, now that Instakit has an acceleration framework that can opportunistically use [Cythonized](http://cython.org/) codepaths for faster processing, it isn’t pure-python anymore, technically. You need Cython installed too, to use these optimizations – although everything still runs fine as pure-python; there’s only [a little bit of cython](https://github.com/fish2000/instakit/blob/master/instakit/processors/ext/halftone.pyx) in master ATM.

If you feel like posting more about your experience installing or using Instakit, please don’t hesitate; I’m happy to document whatever noteworthy issues come up.
