### ISSUE TITLE
No license text included

### ISSUE THREAD

**Issue by fladi** [fish2000/instakit#5]
Could you include the license text of the MIT/Expat license? This is a show-stopper for a future Debian package that I would like to create.

**Comment by fish2000** [comment]
Why sure, I would be happy to – can you direct me to where I might find the official/canonical text of same, for your purposes? Indeed!

**Comment by fladi** [comment]
This should help you out:
http://opensource.org/licenses/MIT

**Comment by fish2000** [comment]
As of commit 23ac799 this license text is included – thanks agains!
